updating script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,38 +1,73 @@
 #!/usr/bin/env bash
 
-# Shamelessly stolen from https://github.com/beardix/asdf-yq/blob/master/bin/list-all#L7
-# Thank you for your great and simple work
+set -eo pipefail
 
-set -o errexit
-set -o nounset
-set -o pipefail
-
-error_exit() {
-  echo "$1" >&2
-  exit "${2:-1}"
+fail() {
+  echo -e "\e[31mFail:\e[m $*"
+  exit 1
 }
 
+get_arch() {
+  local arch="$(uname -m)"
+  echo $arch
+}
 
-install() {
-  declare -r install_type="$1"
-  declare -r download_path="$2"
-  declare -r install_path="$3"
+get_platform() {
+  local platform=""
 
-  if [ "$install_type" == "version" ]; then
-    mkdir "$install_path/bin"
-    mv "$download_path/bin/pint" "$install_path/bin"
-    chmod a+x "$install_path/bin/pint"
-  else
-    cd "$download_path"
-    git submodule update --init --depth=1
-    autoreconf -fi
-    ./configure --disable-maintainer-mode --with-oniguruma=builtin
-    make -j8
-    make check
-    cd "$download_path"
-    mkdir "$install_path/bin/"
-    cp "./pint" "$install_path/bin/"
+  case "$(uname | tr '[:upper:]' '[:lower:]')" in
+    darwin) platform="darwin" ;;
+    linux) platform="linux" ;;
+    windows) platform="windows" ;;
+    *)
+      fail "Platform '$(uname -m)' not supported!"
+      ;;
+  esac
+
+  echo $platform
+}
+
+install_pint() {
+  local install_type=$1
+  local version=$2
+  local install_path=$3
+
+  if [ "$install_type" != "version" ]; then
+    fail "asdf-pint supports release installs only"
   fi
+
+  local download_url
+  platform=$(get_platform)
+  arch=$(get_arch)
+  ext=".tar.gz"
+  if [ "$platform" == "windows" ]; then
+    ext=".zip"
+  fi
+
+  local source_path="${install_path}/bin/pint${ext}"
+  local distination="${install_path}/bin"
+
+  (
+    echo "∗ Downloading and installing pint $version..."
+    mkdir -p "$distination"
+    download_file=$(curl -sq -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/cloudflare/pint/releases" | grep "name" | grep $version | grep $platform | grep $arch | cut -d '"' -f 4)
+    download_url="https://github.com/cloudflare/pint/releases/download/v${version}/$download_file"
+    curl -L "$download_url" >"$source_path" || fail "Could not download $download_url"
+    case $platform in
+      windows)
+        unzip "$source_path" -d "$distination" || fail "Could not uncompress"
+        ;;
+      *)
+        tar zxvf "$source_path" -C "$distination" >/dev/null || fail "Could not uncompress"
+        ;;
+    esac
+
+    rm "$source_path"
+    echo "The pint $version installation was successful!"
+  ) || (
+    rm -rf "$install_path"
+    fail "An error occurred"
+  )
 }
 
-install "$ASDF_INSTALL_TYPE" "$ASDF_DOWNLOAD_PATH" "$ASDF_INSTALL_PATH"
+install_pint "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
